export enum CadastroAcoes {
  Inclusao = 1,
  Edicao = 2,
  Consulta = 3,
  Exclusao = 4,
  Atualizacao = 5,
  Gravacao = 6,
  Copy_Estrutura = 7,
  Sub_Conta = 8,
  Visualizar_Estrtura = 9,
  EdicaoMultipla = 10,
  Inclusao_Ambiente = 20,
  Exclusao_Ambiente = 21,
  Fotos = 22,
  Substituir = 23,
  Trocar = 24,
  None = 99,
}
